//ITEM
export const ITEM_FETCHING = "ITEM_FETCHING";
export const ITEM_SUCCESS = "ITEM_SUCCESS";
export const ITEM_FAILED = "ITEM_FAILED";

export const LOGIN_FETCHING = "LOGIN_FETCHING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

// Register Page
export const REGISTER_FETCHING = "REGISTER_FETCHING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
